version: "3.2"

services:
  
  appserver:
      
    image: bigfathom/application_d7
    #EG image: local/bigfathom/application_d7:latest
    volumes:
      - web-files:/var/www/html:rw
      - bucket-files:/var/local/bigfathom-bucket:rw
    ports:
      - "55580:80"
    expose:
      - "80"
    command: "/var/machine-scripts/startup.sh INIT"
    networks:
      - bigfathom_net
      
  db:
      
    image: mysql
    restart: always
    volumes:
      - db-files:/var/lib/mysql:rw
      
    ports:
      - "43306:3306"    
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: apass2018
      MYSQL_DATABASE: bigfathom_preview
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apass2018
    networks:
      - bigfathom_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOSTS=db
      - PMA_PORT=3306
    restart: always
    ports:
      - 44480:80
    volumes:
      - /sessions
    networks:
      - bigfathom_net
      
volumes:

  web-files:
    external:
      name: appserver_web_bigfathom_preview

  bucket-files:
    external:
      name: appserver_bucket_bigfathom_preview

  db-files:
    external:
      name: db_bigfathom_preview
      
networks:
  bigfathom_net:
    external: false





